# Generated by Django 3.2.5 on 2022-09-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.TextField(max_length=20)),
                ('col2', models.TextField(max_length=20)),
            ],
        ),
    ]
