# Generated by Django 3.2.5 on 2022-09-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trans'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='udt',
            field=models.DateTimeField(auto_now=True, verbose_name='udt'),
        ),
    ]
