# Generated by Django 3.2.5 on 2022-09-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_image_udt'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('tags', models.CharField(max_length=100)),
                ('udt_ip', models.CharField(max_length=15)),
                ('udt', models.DateTimeField(auto_now=True, verbose_name='udt')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Trans',
        ),
    ]
