# Generated by Django 3.2.5 on 2022-09-22 02:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220920_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logfile',
            name='file',
            field=models.FileField(db_index=True, upload_to=core.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='logfile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logfile',
            name='tags',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
